name: Audit

on:
  workflow_dispatch:

jobs:
  anotar-cambios:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar variables de entorno
        id: config-variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "branch=${GITHUB_BRANCH}" >> $GITHUB_ENV
          echo "commitHash=${{ github.sha }}" >> $GITHUB_ENV

      - name: Obtener detalles del commit
        run: |
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an' ${{ github.sha }})
          COMMIT_DATE=$(git log -1 --pretty=format:'%ad' --date=short ${{ github.sha }})
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s' ${{ github.sha }})
          echo "Commit author: $COMMIT_AUTHOR"
          echo "Commit date: $COMMIT_DATE"
          echo "Commit message: $COMMIT_MESSAGE"
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Agregar detalles de commit a CHANGELOG.md
        run: |
          echo "## Commit ${GITHUB_BRANCH} - ${commitHash}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "* **Autor:** ${{ env.COMMIT_AUTHOR }}" >> CHANGELOG.md
          echo "* **Fecha:** ${{ env.COMMIT_DATE }}" >> CHANGELOG.md
          echo "* **Comentario del autor:** ${{ env.COMMIT_MESSAGE }}" >> CHANGELOG.md

      - name: Limpiar directorios temporales
        run: |
          rm -rf node_modules/ && rm -rf bin/*
