name: Audit

on:
  workflow_dispatch:

jobs:
  anotar-cambios:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar variables de entorno
        id: config-variables
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export branch=${GITHUB_BRANCH}
          export commitHash=${{ github.event.commit.id }}

      - name: Obtener detalles del commit
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue: {
                url: 'https://github.com/username/repo/issues/1',
                title: 'Anotación de cambios de commit ${branch} - ${commitHash}',
                body: `
                ${#GITHUB_TOKEN}
                Comite ${branch}
                            
                * Autor: ${{{ github.event.commit.author.name }}}
                * Fecha: ${{{ github.event.commit.date }}}
                * Comentario del autor: ${{{ github.event.commit.message }}}
                            
                `
                              },
                              media:
                              [
                                {
                                  description: 'Detalles del commit',
                                  filetype: 'md',
                                  filename: 'anotacion-cambio-commit.md',
                                  content: `
                ${#GITHUB_TOKEN}
                Comite ${branch}
                            
                * Autor: ${{{ github.event.commit.author.name }}}
                * Fecha: ${{{ github.event.commit.date }}}
                * Comentario del autor: ${{{ github.event.commit.message }}}
                            
                `
                }
              ]
            })

      - name: Agregar detalles de commit a CHANGES.md
        uses: actions/add-file@v4
        with:
          file-path: 'CHANGELOG.md'
          directory: './'

      - name: Limpiar directorios temporales
        run: |
          rm -rf node_modules/ && rm -rf bin/*