name: Schema

on:
  workflow_dispatch:
    branches:
      - feature
  push:
    branches:
      - main

jobs:
  generador-esquema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: checkout_output

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias y jsonschema
        run: npm install -g jsonschema

      - name: Leer templates y generar esquemas
        run: |
          node generate-schemas.js
          # Si deseas agregar algún comando adicional después de ejecutar el script, puedes agregarlo aquí.
