name: Schema

on:
    workflow_dispatch:

jobs:
  generador-esquema:
    runs-on: ubuntu-latest
    steps:
      - name: Agregar dependencias
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NODE_ENV: production

      - name: Instalar jsonschema
        run: npm install json

      - name: Leer templates y generar esquemas
        run: |
          npm run generate-schemas
        # Define la tarea para generar los esquemas
        scripts:
          generate-schemas: 
            template: |
              for file in $(find /templates/*.md); do
                filename=$(basename "$file" | sed 's/.template$//')
                echo "Generando esquema de $filename"
                jsonschema generate --template "$file" -o ./schema/schema-master-$file-v0.0.0.json