name: Schema

on:
    workflow_dispatch:
        branches:
            - feature

jobs:
  generador-esquema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar jsonschema
        run: npm install -g jsonschema

      - name: Leer templates y generar esquemas
        run: node ./bin/generate-schemas.js